name = "OCGOSS Aeronautics"
author = "MangoCat54"
version = "1.42"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9d8bfea176516694374d4503300a8943c1d46c498a0c8b32bcc3c32ede68a0b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
