name = "OCGOSS Aeronautics"
author = "MangoCat54"
version = "1.61"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f75dc672b4fbe194ed0f4bcbaee504cc33d832e573e094229c0b359209ba348"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
