name = "OCGOSS Aeronautics"
author = "MangoCat54"
version = "1.60"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87c05b445e92c66f1dd1da3789fd56d8870abff71a2fb0ca708df1384f64f6c6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
